# page properties
name: Shaina Johl
title: shainerz.github.io
description: shainerz.github.io
url: https://shainerz.github.io

# social metadata
email: shaina.johl@gmail.com
github: https://github.com/shainerz
linkedin: https://www.linkedin.com/in/shainajohl/
phone: 512-516-5734
