# page properties
name: Shaina Johl
title: shainajohl.github.io
description: shainajohl.github.io
url: https://shainajohl.github.io

# social metadata
email: shaina.johl@gmail.com
github: https://github.com/shainerz
linkedin: https://www.linkedin.com/in/shainajohl/
